$ErrorActionPreference = 'Stop'
$base = 'https://clonex.rtfkt.com/'
$files = @(
  'assets/bundle.js',
  'assets/571.bundle.js',
  'assets/b4694e1db54dd7dd32be.otf',
  'assets/192ba3d0cfe383d7af10.otf',
  'assets/71156428a8ad970d24c6.otf',
  'assets/914af9e30f0679d8dc1a.otf',
  'assets/48928b0a1a9a3df51730.otf',
  'world/assets/avatar_multitrack_23_no_tex.glb',
  'world/assets/cables_04.glb',
  'world/assets/camera_opt_7.glb',
  'world/assets/lights-animated_drc.glb',
  'world/assets/murakamiavatar3.glb',
  'world/assets/packavatar/avatars.json',
  'world/assets/packavatar/avatars.png',
  'world/assets/packavatar2/packavatar.json',
  'world/assets/packavatar2/packavatar.png',
  'world/assets/tex/akira_body_albedo1.jpg',
  'world/assets/tex/akira_body_metalness-akira_body_rough.jpg',
  'world/assets/tex/akira_body_normal.jpg',
  'world/assets/tex/crown_albedo.jpg',
  'world/assets/tex/crown_metalness.png',
  'world/assets/tex/crown_normal.jpg',
  'front/apple-touch-icon.png',
  'front/favicon-32x32.png',
  'front/favicon-16x16.png',
  'front/site.webmanifest',
  'front/safari-pinned-tab.svg',
  'front/clonex_share_twitter.jpg',
  'front/rtfkt_akira_40sec_looped.mp3',
  'front/images/loader.jpg',
  'front/images/loader2.png',
  'front/images/distribution.png',
  'front/images/murakami.jpg',
  'front/images/bg-grid-clonex.png',
  'front/images/bg-roadmap-icon.png',
  'front/images/capsule.png',
  'front/images/roadmap/img-1.png',
  'front/images/roadmap/img-2.png',
  'front/images/roadmap/img-3.png',
  'front/images/roadmap/img-4.png',
  'front/images/tutorial/customize.jpg',
  'front/images/tutorial/filter.jpg',
  'front/images/tutorial/pose.jpg',
  'front/lottie/title/img_0.png',
  'front/lottie/title/img_1.png',
  'front/lottie/title/img_2.png',
  'front/lottie/title/img_3.png',
  'front/lottie/title/img_4.png',
  'front/lottie/title/img_5.png',
  'front/lottie/title/img_6.png',
  'front/lottie/title/img_7.png',
  'front/lottie/title/img_8.png',
  'front/lottie/title/img_9.png',
  'front/videos/loop1_60fps.mp4',
  'front/videos/loop1_60fps_00000.jpg',
  'front/videos/loop2_60fps.mp4',
  'front/videos/loop3_60fps.mp4',
  'front/videos/loop3_60fps_00000.jpg',
  'front/videos/vilesmall.mp4',
  'front/videos/vilesmall_00000.jpg',
  'front/arrow_button_background_left.svg',
  'front/arrow_button_background_right.svg',
  'front/label_button_background.svg',
  'front/label_button_background_wide.svg',
  'front/wide_label_button.svg',
  'public/config.json'
)
foreach ($file in $files) {
  $target = Join-Path '.' $file
  New-Item -ItemType Directory -Force (Split-Path $target) | Out-Null
  if (-not (Test-Path $target) -or (Get-Item $target).Length -eq 0) {
    Write-Host "Downloading $file"
    curl.exe -f -sS -L --retry 3 --max-time 300 -o $target ($base + $file)
  }
}
