(function(){
  const hero=document.querySelector('#hero');const stage=document.querySelector('.stage');const video=document.querySelector('#heroVideo');const bar=document.querySelector('.progress i');const uploader=document.querySelector('#uploader');const file=document.querySelector('#videoFile');const length=document.querySelector('#scrollLength');const smooth=document.querySelector('#smoothness');const reset=document.querySelector('#resetVideo');const fallback='front/videos/loop1_60fps.mp4';const isWechat=/MicroMessenger/i.test(navigator.userAgent);let objectUrl='';let target=0;let current=0;let raf=0;let glitchTimer;
  function setLength(){hero.style.height=length.value+'vh';length.nextElementSibling.value=length.value+'vh'}
  function setSmooth(){smooth.nextElementSibling.value=(Number(smooth.value)/100).toFixed(2)}
  function progress(){const distance=hero.offsetHeight-innerHeight;return Math.max(0,Math.min(1,-hero.getBoundingClientRect().top/Math.max(1,distance)))}
  function onScroll(){const p=progress();bar.style.transform=`scaleX(${p})`;if(video.duration&&!isWechat)target=p*Math.max(0,video.duration-.04);stage.classList.add('is-glitch');clearTimeout(glitchTimer);glitchTimer=setTimeout(()=>stage.classList.remove('is-glitch'),90)}
  function draw(){current+=(target-current)*(Number(smooth.value)/100);if(!isWechat&&video.readyState>=2&&Math.abs(video.currentTime-current)>.015)video.currentTime=current;raf=requestAnimationFrame(draw)}
  function load(src){video.pause();video.src=src;video.load();video.addEventListener('loadedmetadata',()=>{current=target=0;if(isWechat){video.loop=true;video.play().catch(()=>{})}else{video.pause();onScroll()}},{once:true})}
  uploader.querySelector('.toggle').onclick=()=>uploader.classList.toggle('open');file.onchange=()=>{if(!file.files[0])return;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file.files[0]);load(objectUrl);uploader.classList.remove('open')};reset.onclick=()=>{if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl='';load(fallback)};length.oninput=setLength;smooth.oninput=setSmooth;addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll,{passive:true});document.addEventListener('WeixinJSBridgeReady',()=>video.play().catch(()=>{}));setLength();setSmooth();onScroll();cancelAnimationFrame(raf);draw();
})();
